#
# /etc/pars.conf - ParsISO Yapılandırması
#

[options]
HoldPkg      = pars glibc systemd linux linux-firmware gcc-runtime
Architecture = auto
SigLevel     = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5

# --- PARS YEREL DEPOLARI (Doğrudan Adres) ---
[pars-stable]
Server = http://localhost:5555/stable/$arch

[pars-security]
Server = http://localhost:5555/security/$arch

# --- ARCH TEMEL DEPOLARI (Base paketler için gerekli) ---
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
